package com.lifeos.app.features.travel.data.datasource

import com.lifeos.app.features.travel.domain.model.AccommodationInfo
import com.lifeos.app.features.travel.domain.model.AiTripSummary
import com.lifeos.app.features.travel.domain.model.BudgetSummary
import com.lifeos.app.features.travel.domain.model.DailyWeather
import com.lifeos.app.features.travel.domain.model.DayPeriod
import com.lifeos.app.features.travel.domain.model.DocumentStatus
import com.lifeos.app.features.travel.domain.model.DocumentType
import com.lifeos.app.features.travel.domain.model.FlightInfo
import com.lifeos.app.features.travel.domain.model.ItineraryActivity
import com.lifeos.app.features.travel.domain.model.ItineraryDay
import com.lifeos.app.features.travel.domain.model.PackingCategory
import com.lifeos.app.features.travel.domain.model.PackingItem
import com.lifeos.app.features.travel.domain.model.PackingItemIcon
import com.lifeos.app.features.travel.domain.model.TravelDocument
import com.lifeos.app.features.travel.domain.model.TravelListData
import com.lifeos.app.features.travel.domain.model.TravelStatistics
import com.lifeos.app.features.travel.domain.model.Trip
import com.lifeos.app.features.travel.domain.model.TripDetail
import com.lifeos.app.features.travel.domain.model.TripStatus
import com.lifeos.app.features.travel.domain.model.WeatherCondition

/**
 * The one place fake Travel data lives, per this task's "keep fake data
 * inside dedicated fake data sources" rule. Holds no business logic —
 * the repositories that call this own the (currently trivial) orchestration.
 *
 * Destinations mirror design/stitch/travel-list.png and
 * design/stitch/travel-details.png exactly (Kyoto, Ubud, Cappadocia, Paris,
 * New York), translated to Turkish country names and date formatting.
 * Cappadocia — this sprint's visual reference — gets the full,
 * mockup-accurate detail content; the others get complete but simpler
 * detail content generated by [genericDetailFor], per this feature's
 * "avoid duplicating Trip fields unnecessarily" scope (see this feature's
 * "Deviations from Stitch" note for why every trip needs *some* detail
 * content, not just Cappadocia).
 *
 * [upcomingTrips] and [savedTripDetails] are mutable so [saveTrip] (added
 * for "Create Travel (AI)") can give real end-to-end closure: a trip
 * generated and saved actually appears in Travel List and opens with its
 * *own* generated content in Travel Detail — not the generic placeholder
 * [genericDetailFor] would otherwise produce for an id it doesn't
 * recognize.
 */
class FakeTravelDataSource {

    private val savedTripDetails = mutableMapOf<String, TripDetail>()
    private var nextGeneratedTripSuffix = 1

    private val upcomingTrips = mutableListOf(
        Trip(
            id = TRIP_ID_KYOTO,
            destinationCity = "Kyoto",
            destinationCountry = "Japonya",
            dateRangeLabel = "12-18 Ekim · 7 Gün",
            status = TripStatus.PLANNED,
            coverImageUrl = "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200",
            isAiOptimized = true,
            daysUntilStart = 14,
            weatherTemperatureCelsius = 22,
            photoCount = null,
        ),
        Trip(
            id = TRIP_ID_UBUD,
            destinationCity = "Ubud",
            destinationCountry = "Endonezya",
            dateRangeLabel = "24-30 Kasım · 6 Gün",
            status = TripStatus.PLANNED,
            coverImageUrl = "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=1200",
            isAiOptimized = false,
            daysUntilStart = 42,
            weatherTemperatureCelsius = 28,
            photoCount = null,
        ),
        Trip(
            id = TRIP_ID_CAPPADOCIA,
            destinationCity = "Kapadokya",
            destinationCountry = "Türkiye",
            dateRangeLabel = "12 Kasım · 4 Gün",
            status = TripStatus.PLANNED,
            coverImageUrl = "https://images.unsplash.com/photo-1641731538990-98de926df457?w=1200",
            isAiOptimized = true,
            daysUntilStart = 4,
            weatherTemperatureCelsius = 12,
            photoCount = null,
        ),
    )

    private val pastTrips = listOf(
        Trip(
            id = TRIP_ID_PARIS,
            destinationCity = "Paris",
            destinationCountry = "Fransa",
            dateRangeLabel = "05-12 Eylül · 7 Gün",
            status = TripStatus.COMPLETED,
            coverImageUrl = "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200",
            isAiOptimized = false,
            daysUntilStart = null,
            weatherTemperatureCelsius = null,
            photoCount = 428,
        ),
        Trip(
            id = TRIP_ID_NEW_YORK,
            destinationCity = "New York",
            destinationCountry = "ABD",
            dateRangeLabel = "20-25 Ağustos · 5 Gün",
            status = TripStatus.COMPLETED,
            coverImageUrl = "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200",
            isAiOptimized = false,
            daysUntilStart = null,
            weatherTemperatureCelsius = null,
            photoCount = 156,
        ),
    )

    fun getTravelList(): TravelListData = TravelListData(
        upcomingTrips = upcomingTrips,
        pastTrips = pastTrips,
        statistics = TravelStatistics(
            // Computed, not a fixed literal — a hardcoded "16" here silently
            // drifted out of sync the moment Cappadocia was added as a third
            // upcoming trip in a previous sprint; deriving it from the same
            // lists getTravelList() itself returns can't drift again.
            totalTripCount = upcomingTrips.size + pastTrips.size + ARCHIVED_TRIP_COUNT,
            countriesVisitedCount = 8,
            upcomingTripCount = upcomingTrips.size,
        ),
        archivedTripCount = ARCHIVED_TRIP_COUNT,
        archivedYearRangeLabel = "2022-2023",
    )

    fun getTripDetail(tripId: String): TripDetail? {
        savedTripDetails[tripId]?.let { return it }
        val trip = (upcomingTrips + pastTrips).find { it.id == tripId } ?: return null
        return if (tripId == TRIP_ID_CAPPADOCIA) cappadociaDetail(trip) else genericDetailFor(trip)
    }

    /**
     * Adds [detail] to Travel List's upcoming trips and remembers its full
     * generated content, so opening it from the list afterward shows what
     * was actually generated/saved — not [genericDetailFor]'s placeholder.
     */
    fun saveTrip(detail: TripDetail) {
        upcomingTrips.add(detail.trip)
        savedTripDetails[detail.trip.id] = detail
    }

    /**
     * A stable, unique-per-session id for a freshly generated draft — a
     * simple incrementing suffix rather than [kotlin.random.Random], since
     * each call here really is creating a new, distinct record (unlike the
     * flight-number bug elsewhere in this class, where the same fake trip
     * needed the *same* number on every read).
     */
    fun nextGeneratedTripId(): String = "trip-generated-${nextGeneratedTripSuffix++}"

    private fun cappadociaDetail(trip: Trip): TripDetail = TripDetail(
        trip = trip,
        aiSummary = AiTripSummary(
            highlightMessage = "En iyi balon uçuşu zamanı yarın saat 05:30. Hafif rüzgarlar, vadi " +
                "üzerinde sakin ve manzaralı bir yolculuk için ideal koşullar sağlıyor.",
            weatherTemperatureCelsius = 12,
            windSpeedKmh = 4,
        ),
        itinerary = listOf(
            ItineraryDay(
                dayNumber = 1,
                title = "Varış ve Mağara Otele Giriş",
                activities = listOf(
                    ItineraryActivity(DayPeriod.MORNING, "Kapadokya'ya varış ve otele transfer"),
                    ItineraryActivity(DayPeriod.AFTERNOON, "Göreme'deki mağara süitinize yerleşin"),
                    ItineraryActivity(DayPeriod.EVENING, "Antik kasaba merkezinde akşam yürüyüşü"),
                ),
                photoUrls = listOf(
                    "https://images.unsplash.com/photo-1580977276076-ae4b8c219b8e?w=400",
                    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400",
                ),
                bookingActionLabel = null,
            ),
            ItineraryDay(
                dayNumber = 2,
                title = "Gün Doğumu Uçuşu ve Göreme Vadisi",
                activities = listOf(
                    ItineraryActivity(DayPeriod.MORNING, "Muhteşem bir saatlik balon uçuşu"),
                    ItineraryActivity(DayPeriod.AFTERNOON, "Açık Hava Müzesi ziyareti"),
                    ItineraryActivity(DayPeriod.EVENING, "Aşk Vadisi'nde yürüyüş"),
                ),
                photoUrls = emptyList(),
                bookingActionLabel = "Rezervasyonu Yönet",
            ),
        ),
        flight = FlightInfo(
            airline = "Turkish Airlines",
            flightNumber = "TK2014",
            departureAirport = "İstanbul (IST)",
            departureTimeLabel = "10:45",
            arrivalAirport = "Nevşehir (NAV)",
            arrivalTimeLabel = "12:15",
            terminal = "Dış Hatlar Terminali",
            gate = null,
        ),
        accommodation = AccommodationInfo(
            hotelName = "Museum Hotel",
            address = "Tekelli Mahallesi, Göreme, Nevşehir",
            roomType = "Deluxe Mağara Süiti",
            checkInLabel = "15:00",
            checkOutLabel = "11:00",
        ),
        weatherForecast = listOf(
            DailyWeather("Bugün", 12, WeatherCondition.SUNNY),
            DailyWeather("Yarın", 14, WeatherCondition.SUNNY),
            DailyWeather("Çar", 10, WeatherCondition.CLOUDY),
            DailyWeather("Per", 9, WeatherCondition.WINDY),
            DailyWeather("Cum", 11, WeatherCondition.SUNNY),
        ),
        budget = BudgetSummary(
            totalBudget = 2800,
            spentAmount = 1250,
            accommodationCost = 600,
            transportationCost = 350,
            foodCost = 180,
            activitiesCost = 120,
        ),
        packingCategories = listOf(
            PackingCategory(
                name = "Genel",
                items = listOf(
                    PackingItem("pack-camera", "Kamera ekipmanı", true, PackingItemIcon.CAMERA),
                    PackingItem("pack-jacket", "Kalın mont", true, PackingItemIcon.COLD_WEATHER),
                    PackingItem("pack-boots", "Yürüyüş botları", true, PackingItemIcon.FOOTWEAR),
                    PackingItem("pack-powerbank", "Powerbank", false, PackingItemIcon.ELECTRONICS),
                ),
            ),
            PackingCategory(
                name = "Belgeler",
                items = listOf(
                    PackingItem("pack-passport-copy", "Kimlik fotokopisi", false, PackingItemIcon.DOCUMENTS),
                    PackingItem("pack-insurance-doc", "Sigorta belgesi", false, PackingItemIcon.DOCUMENTS),
                ),
            ),
            PackingCategory(
                name = "Kişisel Bakım",
                items = listOf(
                    PackingItem("pack-sunscreen", "Güneş kremi", false, PackingItemIcon.TOILETRIES),
                    PackingItem("pack-lipbalm", "Dudak nemlendirici", false, PackingItemIcon.TOILETRIES),
                ),
            ),
        ),
        documents = listOf(
            TravelDocument(DocumentType.PASSPORT, DocumentStatus.READY),
            TravelDocument(DocumentType.VISA, DocumentStatus.READY),
            TravelDocument(DocumentType.INSURANCE, DocumentStatus.PENDING),
            TravelDocument(DocumentType.BOARDING_PASS, DocumentStatus.MISSING),
        ),
        notes = "",
    )

    /**
     * Complete but simpler detail content for every trip other than
     * Cappadocia — hand-authoring five full mockup-depth detail sets would
     * mostly duplicate Cappadocia's shape with different words, so the
     * other trips share this generator instead, keyed off [trip]'s own
     * fields where it matters (destination, dates, AI-optimized flag).
     */
    private fun genericDetailFor(trip: Trip): TripDetail = TripDetail(
        trip = trip,
        aiSummary = AiTripSummary(
            highlightMessage = if (trip.isAiOptimized) {
                "${trip.destinationCity} için en iyi gezi planı hazır. Hava durumu ve yerel etkinlikler " +
                    "dikkate alınarak güzergahınız optimize edildi."
            } else {
                "${trip.destinationCity} seyahatiniz için genel öneriler hazırlanıyor."
            },
            weatherTemperatureCelsius = trip.weatherTemperatureCelsius ?: 20,
            windSpeedKmh = 10,
        ),
        itinerary = listOf(
            ItineraryDay(
                dayNumber = 1,
                title = "${trip.destinationCity}'a Varış",
                activities = listOf(
                    ItineraryActivity(DayPeriod.MORNING, "Uçuş ve transfer"),
                    ItineraryActivity(DayPeriod.AFTERNOON, "Otele yerleşme"),
                    ItineraryActivity(DayPeriod.EVENING, "Çevreyi keşfetme"),
                ),
                photoUrls = emptyList(),
                bookingActionLabel = null,
            ),
            ItineraryDay(
                dayNumber = 2,
                title = "${trip.destinationCity} Keşfi",
                activities = listOf(
                    ItineraryActivity(DayPeriod.MORNING, "Şehir turu"),
                    ItineraryActivity(DayPeriod.AFTERNOON, "Yerel lezzetler"),
                    ItineraryActivity(DayPeriod.EVENING, "Serbest zaman"),
                ),
                photoUrls = emptyList(),
                bookingActionLabel = "Rezervasyonu Yönet",
            ),
        ),
        flight = FlightInfo(
            airline = "Turkish Airlines",
            // A stable, deterministic per-trip number — not real randomness,
            // which would make this fake value change on every reload.
            flightNumber = "TK${100 + (trip.id.hashCode().mod(900))}",
            departureAirport = "İstanbul (IST)",
            departureTimeLabel = "09:30",
            arrivalAirport = "${trip.destinationCity} Havalimanı",
            arrivalTimeLabel = "—",
            terminal = "Dış Hatlar Terminali",
            gate = null,
        ),
        accommodation = AccommodationInfo(
            hotelName = "${trip.destinationCity} Merkez Otel",
            address = "${trip.destinationCity}, ${trip.destinationCountry}",
            roomType = "Standart Oda",
            checkInLabel = "14:00",
            checkOutLabel = "12:00",
        ),
        weatherForecast = listOf(
            DailyWeather("Bugün", trip.weatherTemperatureCelsius ?: 20, WeatherCondition.SUNNY),
            DailyWeather("Yarın", (trip.weatherTemperatureCelsius ?: 20) - 1, WeatherCondition.CLOUDY),
            DailyWeather("Çar", (trip.weatherTemperatureCelsius ?: 20) + 1, WeatherCondition.SUNNY),
        ),
        budget = BudgetSummary(
            totalBudget = 2000,
            spentAmount = 400,
            accommodationCost = 250,
            transportationCost = 100,
            foodCost = 30,
            activitiesCost = 20,
        ),
        packingCategories = listOf(
            PackingCategory(
                name = "Genel",
                items = listOf(
                    PackingItem("pack-generic-clothes", "Kıyafetler", false, PackingItemIcon.GENERAL),
                    PackingItem("pack-generic-electronics", "Şarj cihazları", false, PackingItemIcon.ELECTRONICS),
                ),
            ),
        ),
        documents = listOf(
            TravelDocument(DocumentType.PASSPORT, DocumentStatus.READY),
            TravelDocument(DocumentType.VISA, DocumentStatus.PENDING),
            TravelDocument(DocumentType.INSURANCE, DocumentStatus.MISSING),
            TravelDocument(DocumentType.BOARDING_PASS, DocumentStatus.MISSING),
        ),
        notes = "",
    )

    private companion object {
        const val TRIP_ID_KYOTO = "trip-kyoto"
        const val TRIP_ID_UBUD = "trip-ubud"
        const val TRIP_ID_CAPPADOCIA = "trip-cappadocia"
        const val TRIP_ID_PARIS = "trip-paris"
        const val TRIP_ID_NEW_YORK = "trip-new-york"
        const val ARCHIVED_TRIP_COUNT = 12
    }
}
